/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaUm;

import javax.swing.JOptionPane;

/**
 *
 * @author messi
 */
public class IniciaRestaUmGrafico extends javax.swing.JFrame {

    Tabuleiro tabuleiro_pronto;
    Tabuleiro tabuleiro_final;
    Integer faseBotaoDeStart = 0;
    
    public IniciaRestaUmGrafico() {
        initComponents();
    }

    private void start(){
        if (faseBotaoDeStart == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Campo para o quadrante vazio comecar e clicke em Next");
            jButton_Start.setText("Next");
            faseBotaoDeStart++;
        } else if (faseBotaoDeStart == 1) {
            JOptionPane.showMessageDialog(this, "Selecione um Campo para o peao terminar e clicke em Next");   
            faseBotaoDeStart++;         
        } else {
            new Thread(() -> comecaSolucao()).start();
        }
    }
    
    private void comecaSolucao(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Matriz = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        p02 = new javax.swing.JCheckBox();
        p03 = new javax.swing.JCheckBox();
        p04 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        p12 = new javax.swing.JCheckBox();
        p13 = new javax.swing.JCheckBox();
        p16 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        p20 = new javax.swing.JCheckBox();
        p21 = new javax.swing.JCheckBox();
        p22 = new javax.swing.JCheckBox();
        p23 = new javax.swing.JCheckBox();
        p24 = new javax.swing.JCheckBox();
        p25 = new javax.swing.JCheckBox();
        p26 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        p30 = new javax.swing.JCheckBox();
        p31 = new javax.swing.JCheckBox();
        p32 = new javax.swing.JCheckBox();
        p33 = new javax.swing.JCheckBox();
        p34 = new javax.swing.JCheckBox();
        p35 = new javax.swing.JCheckBox();
        p36 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        p40 = new javax.swing.JCheckBox();
        p41 = new javax.swing.JCheckBox();
        p42 = new javax.swing.JCheckBox();
        p43 = new javax.swing.JCheckBox();
        p44 = new javax.swing.JCheckBox();
        p45 = new javax.swing.JCheckBox();
        p46 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        p52 = new javax.swing.JCheckBox();
        p53 = new javax.swing.JCheckBox();
        p54 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        p62 = new javax.swing.JCheckBox();
        p63 = new javax.swing.JCheckBox();
        p64 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton_Start = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(675, 308));
        setPreferredSize(new java.awt.Dimension(675, 308));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel_Matriz.setMinimumSize(new java.awt.Dimension(136, 166));
        jPanel_Matriz.setPreferredSize(new java.awt.Dimension(104, 38));
        jPanel_Matriz.setLayout(new javax.swing.BoxLayout(jPanel_Matriz, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        p02.setSelected(true);
        jPanel1.add(p02);

        p03.setSelected(true);
        jPanel1.add(p03);

        p04.setSelected(true);
        jPanel1.add(p04);

        jPanel_Matriz.add(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));

        p12.setSelected(true);
        jPanel2.add(p12);

        p13.setSelected(true);
        jPanel2.add(p13);

        p16.setSelected(true);
        jPanel2.add(p16);

        jPanel_Matriz.add(jPanel2);

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(104, 38));

        p20.setSelected(true);
        jPanel3.add(p20);

        p21.setSelected(true);
        jPanel3.add(p21);

        p22.setSelected(true);
        jPanel3.add(p22);

        p23.setSelected(true);
        jPanel3.add(p23);

        p24.setSelected(true);
        jPanel3.add(p24);

        p25.setSelected(true);
        jPanel3.add(p25);

        p26.setSelected(true);
        jPanel3.add(p26);

        jPanel_Matriz.add(jPanel3);

        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(104, 38));

        p30.setSelected(true);
        jPanel4.add(p30);

        p31.setSelected(true);
        jPanel4.add(p31);

        p32.setSelected(true);
        jPanel4.add(p32);

        p33.setSelected(true);
        jPanel4.add(p33);

        p34.setSelected(true);
        jPanel4.add(p34);

        p35.setSelected(true);
        jPanel4.add(p35);

        p36.setSelected(true);
        jPanel4.add(p36);

        jPanel_Matriz.add(jPanel4);

        jPanel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(104, 38));

        p40.setSelected(true);
        jPanel5.add(p40);

        p41.setSelected(true);
        jPanel5.add(p41);

        p42.setSelected(true);
        jPanel5.add(p42);

        p43.setSelected(true);
        jPanel5.add(p43);

        p44.setSelected(true);
        jPanel5.add(p44);

        p45.setSelected(true);
        jPanel5.add(p45);

        p46.setSelected(true);
        jPanel5.add(p46);

        jPanel_Matriz.add(jPanel5);

        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));

        p52.setSelected(true);
        jPanel6.add(p52);

        p53.setSelected(true);
        jPanel6.add(p53);

        p54.setSelected(true);
        jPanel6.add(p54);

        jPanel_Matriz.add(jPanel6);

        jPanel7.setMinimumSize(new java.awt.Dimension(0, 0));

        p62.setSelected(true);
        jPanel7.add(p62);

        p63.setSelected(true);
        jPanel7.add(p63);

        p64.setSelected(true);
        jPanel7.add(p64);

        jPanel_Matriz.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel_Matriz.add(jPanel8);

        jPanel10.setPreferredSize(new java.awt.Dimension(104, 38));

        jButton_Start.setText("Start");
        jButton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Start);

        jPanel_Matriz.add(jPanel10);

        getContentPane().add(jPanel_Matriz);

        jPanel9.setMinimumSize(new java.awt.Dimension(320, 240));
        jPanel9.setPreferredSize(new java.awt.Dimension(320, 240));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.addTab("Log", jScrollPane1);

        jPanel9.add(jTabbedPane1);

        getContentPane().add(jPanel9);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartActionPerformed
        start();
    }//GEN-LAST:event_jButton_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciaRestaUmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciaRestaUmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciaRestaUmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciaRestaUmGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciaRestaUmGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Start;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Matriz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox p02;
    private javax.swing.JCheckBox p03;
    private javax.swing.JCheckBox p04;
    private javax.swing.JCheckBox p12;
    private javax.swing.JCheckBox p13;
    private javax.swing.JCheckBox p16;
    private javax.swing.JCheckBox p20;
    private javax.swing.JCheckBox p21;
    private javax.swing.JCheckBox p22;
    private javax.swing.JCheckBox p23;
    private javax.swing.JCheckBox p24;
    private javax.swing.JCheckBox p25;
    private javax.swing.JCheckBox p26;
    private javax.swing.JCheckBox p30;
    private javax.swing.JCheckBox p31;
    private javax.swing.JCheckBox p32;
    private javax.swing.JCheckBox p33;
    private javax.swing.JCheckBox p34;
    private javax.swing.JCheckBox p35;
    private javax.swing.JCheckBox p36;
    private javax.swing.JCheckBox p40;
    private javax.swing.JCheckBox p41;
    private javax.swing.JCheckBox p42;
    private javax.swing.JCheckBox p43;
    private javax.swing.JCheckBox p44;
    private javax.swing.JCheckBox p45;
    private javax.swing.JCheckBox p46;
    private javax.swing.JCheckBox p52;
    private javax.swing.JCheckBox p53;
    private javax.swing.JCheckBox p54;
    private javax.swing.JCheckBox p62;
    private javax.swing.JCheckBox p63;
    private javax.swing.JCheckBox p64;
    // End of variables declaration//GEN-END:variables
}
